version: "3.9"
services:
  postgres: 
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
     - 5432:5432
  
  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
     - 8081:8081
    environment:
     - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
