openapi: 3.0.0
info:
  version: 1.0.0
  title: URL shortener


paths:
  /api/v1/health:
    get:
      description: Returns health status of all app services
      responses:
        200:
          description: All services are healthy and working.
          content:
            application/json:
              examples:
                healthy:
                  summary: Services are properly working
                  value: { "status": "healthy","services": { "db": "ok" } }

        503:
          description: Some services can have degraded performance or can be unreachable.
          content:
            application/json:
              examples:
                healthy:
                  summary: Services are not properly working
                  value: { "status": "unhealthy","services": { "db": "fail" } }
