name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: [ubuntu-latest]
    container: python:3.10
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with dev

      - name: Run migrations
        run: poetry run alembic upgrade head

      - name: Run linting
        run: poetry run flake8

      - name: Run tests
        run: poetry run python -m pytest
